// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUEVcZ25wuZdSa69coGoYGM-OozN-7wAA',
    appId: '1:666300135228:web:a9ae4f6da0c5b8be785039',
    messagingSenderId: '666300135228',
    projectId: 'gemastik-softdev',
    authDomain: 'gemastik-softdev.firebaseapp.com',
    storageBucket: 'gemastik-softdev.appspot.com',
    measurementId: 'G-R8BQJ7WE2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwXVdXU7VlslJbfK8jk580SAa6VPAZok',
    appId: '1:666300135228:android:9fd75d03c0f6e2e5785039',
    messagingSenderId: '666300135228',
    projectId: 'gemastik-softdev',
    storageBucket: 'gemastik-softdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsDaT5sfX4-GfjM84uhIkfzJfQjNJdIPI',
    appId: '1:666300135228:ios:5b651e3fe956f469785039',
    messagingSenderId: '666300135228',
    projectId: 'gemastik-softdev',
    storageBucket: 'gemastik-softdev.appspot.com',
    iosBundleId: 'com.example.semaraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsDaT5sfX4-GfjM84uhIkfzJfQjNJdIPI',
    appId: '1:666300135228:ios:5b651e3fe956f469785039',
    messagingSenderId: '666300135228',
    projectId: 'gemastik-softdev',
    storageBucket: 'gemastik-softdev.appspot.com',
    iosBundleId: 'com.example.semaraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUEVcZ25wuZdSa69coGoYGM-OozN-7wAA',
    appId: '1:666300135228:web:2e51fe194d85716c785039',
    messagingSenderId: '666300135228',
    projectId: 'gemastik-softdev',
    authDomain: 'gemastik-softdev.firebaseapp.com',
    storageBucket: 'gemastik-softdev.appspot.com',
    measurementId: 'G-NGJH62QSY7',
  );
}
